# Local build
FROM gradle:7.6-jdk17-jammy AS builder-local

WORKDIR /driver/corda
ADD build /driver/corda/build

FROM builder-local as builder

# Deployment Image 
FROM eclipse-temurin:17-jre-noble

COPY --from=builder /driver/corda/build/install/driver-corda /driver/corda/

WORKDIR /driver/corda

ARG GIT_URL
LABEL org.opencontainers.image.source ${GIT_URL}
