# Remote build
FROM gradle:4.10.3-jdk8 AS builder-remote

USER root
RUN apt-get update && apt-get install -y maven

WORKDIR /driver/corda
ADD . .
RUN ./gradlew clean installDist

FROM builder-remote as builder

# Deployment Image 
FROM openjdk:8-jre

COPY --from=builder /driver/corda/build/install/driver-corda /driver/corda/

WORKDIR /driver/corda

ARG GIT_URL
LABEL org.opencontainers.image.source ${GIT_URL}
