name: 'Copm Test'
description: "common setup steps for the weaver network needed to run copm tests"
inputs:
  github-actor:  
    description: the github actor variable
    required: true
  github-token:
    description: the github secret token variable
    required: true
runs:
  using: "composite"
  steps:
    - name: free github runner disk space
      shell: bash
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Use Node.js ${{ env.NODEJS_VERSION }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
      with:
        node-version: ${{ env.NODEJS_VERSION }}
    - id: yarn-cache
      name: Restore Yarn Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
      with:
        key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
        path: ./.yarn/
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
    - name: Get Latest Relay Dependencies
      shell: bash
      run: |
        make protos-local
        cargo update -p nom
        cargo update -p lexical-core
      working-directory: weaver/core/relay
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #v6.5.0
      with:
        go-version: '1.26.4'
    - name: Use Protoc 3.15
      shell: bash
      run: |
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/protoc-3.15.6-linux-x86_64.zip
        unzip protoc-3.15.6-linux-x86_64.zip -d protoc
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0
    - name: Set up JDK 17
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 #v5.4.0
      with:
          java-version: '17'
          distribution: 'adopt'
    - name: Generate github.properties
      shell: bash
      run: |
            echo "Using ${{ inputs.github-actor }} user."
            { 
              echo "username=${{ inputs.github-actor }}" 
              echo "password=${{ inputs.github-token }}" 
              echo "url=https://maven.pkg.github.com/hyperledger-cacti/cacti"
            } >> github.properties
            {
              echo "username=${{ inputs.github-actor }}"
              echo "password=${{ inputs.github-token }}"
              echo "url=https://maven.pkg.github.com/hyperledger-cacti/cacti" 
            } >> github.main.properties
      working-directory: weaver/tests/network-setups/corda


