base-class:
	cp -r ../../core/network/fabric-interop-cc/interfaces/asset-mgmt .
	cp -r ../../core/network/fabric-interop-cc/contracts/interop/mocks asset-mgmt/.
	cp -r ../../core/network/fabric-interop-cc/contracts/interop/mocks .
clean:
	rm -rf asset-mgmt
	rm -rf mocks
