pipeline {
    agent any

    options {

      // We only keep the most recent five builds.
      buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5'))

    }

    environment {
      DOCKER_CREDENTIALS = credentials('sannish.artifactory.apikey')
      DOCKER_REGISTRY = 'res-dlt-interop-docker-local.artifactory.swg-devops.com'
    }

    stages {

        stage('Docker Login') {
            steps {
              sh '''
                  docker login -u ${DOCKER_CREDENTIALS_USR} -p ${DOCKER_CREDENTIALS_PSW} ${DOCKER_REGISTRY}
               '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                  sed -e "s/<IBM email>/${DOCKER_CREDENTIALS_USR}/g" -e "s/<Artifactory API Key>/${DOCKER_CREDENTIALS_PSW}/g" github.properties.template > github.properties;
                  docker build -t corda-cli:latest .;
            		'''
            }
        }


      	stage('Push') {
          steps {
             sh '''
          		 docker tag corda-cli:latest ${DOCKER_REGISTRY}/dlt-interop/corda-cli:latest
          		 docker push ${DOCKER_REGISTRY}/dlt-interop/corda-cli:latest
             '''
           }
         }

    }

    post {

      always {
      	sh '''
               docker logout ${DOCKER_REGISTRY}
            '''
      }
      success {
          setBuildStatus("Build complete", "SUCCESS");
          slackSend (color: '#00FF00', message: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
      }

      failure {
          setBuildStatus("Build failure", "FAILURE");
      }
    }
}

void setBuildStatus(String message, String state) {
  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.ibm.com/dlt-interoperability/relay.git"],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/build-status"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}
