{
 "title": "Performance Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Gas Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(operation_gas_used)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Exchanged Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(value_exchanged_USD_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(initiated_transactions_total)",
     "legendFormat": "Initiated"
    },
    {
     "expr": "sum(successful_transactions_total)",
     "legendFormat": "Successful"
    },
    { "expr": "sum(failed_transactions_total)", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Transaction Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "transaction_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Operation Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "operation_duration_milliseconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}