# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.provider "hyperv"

  config.vm.network "public_network", bridge: "Default Switch"

  config.vm.provider :hyperv do |hyperv|
    hyperv.vmname = "CACTUS-CI-Box"
    hyperv.maxmemory = 16384
    hyperv.cpus = 4
  end

  config.vm.provision "shell", path: "tools/configure.sh"

end
