besu:
	bash scripts/setupNetwork.sh

clean:
	tmux kill-session -t EthSigner_session
	tmux kill-session -t Node-1_session
	tmux kill-session -t Node-2_session
	tmux kill-session -t Node-3_session
	tmux kill-session -t Node-4_session
	rm -rf SampleBesuNetwork/

