// source: common/asset_transfer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.common.asset_transfer.AssetClaimStatus', null, global);
goog.exportSymbol('proto.common.asset_transfer.AssetPledge', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.common.asset_transfer.AssetPledge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.common.asset_transfer.AssetPledge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.common.asset_transfer.AssetPledge.displayName = 'proto.common.asset_transfer.AssetPledge';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.common.asset_transfer.AssetClaimStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.common.asset_transfer.AssetClaimStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.common.asset_transfer.AssetClaimStatus.displayName = 'proto.common.asset_transfer.AssetClaimStatus';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.common.asset_transfer.AssetPledge.prototype.toObject = function(opt_includeInstance) {
  return proto.common.asset_transfer.AssetPledge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.common.asset_transfer.AssetPledge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.asset_transfer.AssetPledge.toObject = function(includeInstance, msg) {
  var f, obj = {
    assetdetails: msg.getAssetdetails_asB64(),
    localnetworkid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    remotenetworkid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    recipient: jspb.Message.getFieldWithDefault(msg, 4, ""),
    expirytimesecs: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.common.asset_transfer.AssetPledge}
 */
proto.common.asset_transfer.AssetPledge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.common.asset_transfer.AssetPledge;
  return proto.common.asset_transfer.AssetPledge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.common.asset_transfer.AssetPledge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.common.asset_transfer.AssetPledge}
 */
proto.common.asset_transfer.AssetPledge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAssetdetails(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocalnetworkid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRemotenetworkid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRecipient(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setExpirytimesecs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.common.asset_transfer.AssetPledge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.common.asset_transfer.AssetPledge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.common.asset_transfer.AssetPledge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.asset_transfer.AssetPledge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAssetdetails_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getLocalnetworkid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRemotenetworkid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRecipient();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getExpirytimesecs();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
};


/**
 * optional bytes assetDetails = 1;
 * @return {!(string|Uint8Array)}
 */
proto.common.asset_transfer.AssetPledge.prototype.getAssetdetails = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes assetDetails = 1;
 * This is a type-conversion wrapper around `getAssetdetails()`
 * @return {string}
 */
proto.common.asset_transfer.AssetPledge.prototype.getAssetdetails_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAssetdetails()));
};


/**
 * optional bytes assetDetails = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAssetdetails()`
 * @return {!Uint8Array}
 */
proto.common.asset_transfer.AssetPledge.prototype.getAssetdetails_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAssetdetails()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.common.asset_transfer.AssetPledge} returns this
 */
proto.common.asset_transfer.AssetPledge.prototype.setAssetdetails = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string localNetworkID = 2;
 * @return {string}
 */
proto.common.asset_transfer.AssetPledge.prototype.getLocalnetworkid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.asset_transfer.AssetPledge} returns this
 */
proto.common.asset_transfer.AssetPledge.prototype.setLocalnetworkid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string remoteNetworkID = 3;
 * @return {string}
 */
proto.common.asset_transfer.AssetPledge.prototype.getRemotenetworkid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.asset_transfer.AssetPledge} returns this
 */
proto.common.asset_transfer.AssetPledge.prototype.setRemotenetworkid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string recipient = 4;
 * @return {string}
 */
proto.common.asset_transfer.AssetPledge.prototype.getRecipient = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.asset_transfer.AssetPledge} returns this
 */
proto.common.asset_transfer.AssetPledge.prototype.setRecipient = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional uint64 expiryTimeSecs = 5;
 * @return {number}
 */
proto.common.asset_transfer.AssetPledge.prototype.getExpirytimesecs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.common.asset_transfer.AssetPledge} returns this
 */
proto.common.asset_transfer.AssetPledge.prototype.setExpirytimesecs = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.common.asset_transfer.AssetClaimStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.common.asset_transfer.AssetClaimStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.asset_transfer.AssetClaimStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    assetdetails: msg.getAssetdetails_asB64(),
    localnetworkid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    remotenetworkid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    recipient: jspb.Message.getFieldWithDefault(msg, 4, ""),
    claimstatus: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    expirytimesecs: jspb.Message.getFieldWithDefault(msg, 6, 0),
    expirationstatus: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.common.asset_transfer.AssetClaimStatus}
 */
proto.common.asset_transfer.AssetClaimStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.common.asset_transfer.AssetClaimStatus;
  return proto.common.asset_transfer.AssetClaimStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.common.asset_transfer.AssetClaimStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.common.asset_transfer.AssetClaimStatus}
 */
proto.common.asset_transfer.AssetClaimStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAssetdetails(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocalnetworkid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRemotenetworkid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRecipient(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setClaimstatus(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setExpirytimesecs(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExpirationstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.common.asset_transfer.AssetClaimStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.common.asset_transfer.AssetClaimStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.asset_transfer.AssetClaimStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAssetdetails_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getLocalnetworkid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRemotenetworkid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRecipient();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getClaimstatus();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getExpirytimesecs();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getExpirationstatus();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional bytes assetDetails = 1;
 * @return {!(string|Uint8Array)}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getAssetdetails = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes assetDetails = 1;
 * This is a type-conversion wrapper around `getAssetdetails()`
 * @return {string}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getAssetdetails_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAssetdetails()));
};


/**
 * optional bytes assetDetails = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAssetdetails()`
 * @return {!Uint8Array}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getAssetdetails_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAssetdetails()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.common.asset_transfer.AssetClaimStatus} returns this
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.setAssetdetails = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string localNetworkID = 2;
 * @return {string}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getLocalnetworkid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.asset_transfer.AssetClaimStatus} returns this
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.setLocalnetworkid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string remoteNetworkID = 3;
 * @return {string}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getRemotenetworkid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.asset_transfer.AssetClaimStatus} returns this
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.setRemotenetworkid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string recipient = 4;
 * @return {string}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getRecipient = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.asset_transfer.AssetClaimStatus} returns this
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.setRecipient = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool claimStatus = 5;
 * @return {boolean}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getClaimstatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.common.asset_transfer.AssetClaimStatus} returns this
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.setClaimstatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional uint64 expiryTimeSecs = 6;
 * @return {number}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getExpirytimesecs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.common.asset_transfer.AssetClaimStatus} returns this
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.setExpirytimesecs = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bool expirationStatus = 7;
 * @return {boolean}
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.getExpirationstatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.common.asset_transfer.AssetClaimStatus} returns this
 */
proto.common.asset_transfer.AssetClaimStatus.prototype.setExpirationstatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


goog.object.extend(exports, proto.common.asset_transfer);
