export const DEFAULT_PORT_GATEWAY_SERVER = 3010;
export const DEFAULT_PORT_GATEWAY_CLIENT = DEFAULT_PORT_GATEWAY_SERVER + 1;
export const DEFAULT_PORT_GATEWAY_UI = DEFAULT_PORT_GATEWAY_SERVER + 2;
export const SATP_VERSION = "v02";