{
 "title": "Financial Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Value Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(value_exchanged_total{transaction_direction=\"sent\"})",
     "legendFormat": "Total Value Sent"
    }
   ]
  },
  {
   "title": "Total Value Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(value_exchanged_total{transaction_direction=\"received\"})",
     "legendFormat": "Total Value Received"
    }
   ]
  },
  {
   "title": "Operation Gas Used",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(operation) (operation_gas_used)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(successful_transactions_total)",
     "legendFormat": "Successful Transactions"
    },
    { "expr": "sum(ongoing_transactions)", "legendFormat": "Ongoing Transactions" }
   ]
  },
  {
   "title": "Transaction Gas Used",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "transaction_gas_used", "legendFormat": "__auto" }
   ]
  }
 ]
}