{
 "title": "System Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Number of Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "created_sessions_total", "legendFormat": "Created Sessions" }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(successful_transactions_total)",
     "legendFormat": "Successful Transactions"
    },
    { "expr": "failed_transactions_total", "legendFormat": "Failed Transactions" }
   ]
  },
  {
   "title": "Connected DLTs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "connected_DLTs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Supported Assets",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_supported_assets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gateways",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gateways", "legendFormat": "__auto" }
   ]
  }
 ]
}