#!/bin/sh
echo "pre-push hook, running SATP linter"
yarn lerna run lint:ci --scope=@hyperledger/cactus-plugin-satp-hermes
if [ $? -ne 0 ]; then
	echo "Lint failed. Please fix errors before pushing."
	exit 1
fi
