@startuml leader-election-etcd-leases-deployment-caption
!include <tupadr3/common>
!include <office/Servers/database_server>
!include <office/Servers/application_server>

center header
Hyperledger Cactus

endheader

title
  <u>Leader Election Deployment Diagram</u>

end title

center footer Hyperledger Cactus, 2019

frame Cactus {

  frame Etcd_Cluster as ec {
    OFF_DATABASE_SERVER(etcd1,"Etcd 1")
    OFF_DATABASE_SERVER(etcd2,"Etcd 2")
    OFF_DATABASE_SERVER(etcdn,"Etcd N")
  }

  frame Validator_Cluster as vc {
    OFF_APPLICATION_SERVER(bvn1,"Validator 1")
    OFF_APPLICATION_SERVER(bvn2,"Validator 2")
    OFF_APPLICATION_SERVER(bvnn,"Validator N")
  }

}

bvn2 <~~> bvnn
bvn1 <~> bvn2
bvn1 <~> bvnn

etcd1 <~~> etcd2
etcd1 <~> etcdn
etcd2 <~> etcdn

bvn1 <=[#blue]=> ec
bvn2 <=[#blue]=> ec
bvnn <=[#blue]=> ec

@enduml
