@startuml state-diagram-validator

title \n<u>Leader Election State Diagram</u>\n
footer \nHyperledger Cactus, 2019

[*] --> Started
Started --> Candidate
Started: NodeJS process

Candidate : Attempts to obtain\ngrant on lease\nof Etcd key
Leader: Sets Etcd key to\n it's own identity
Follower: Watches Etcd\nkey to determine\nleader's identity

Candidate -> Follower: lease denied
Follower -> Candidate: lease TTL expire
Leader -> Candidate: lease TTL expire
Candidate -> Leader: lease granted

Candidate --> Terminated
Follower --> Terminated
Leader --> Terminated

Terminated --> [*]

@enduml
