name: ghpkg-all-kotlin-api-clients-publish

env:
  NODEJS_VERSION: v20.20.0

on:
  # Publish `v1.2.3` tags as releases.
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Indy SDK
      run: >
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 \
          && sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic stable" \
          && sudo apt-get update \
          && sudo apt-get install -y \
              libindy \
              libnullpay \
              libvcx \
              indy-cli \
          && sudo rm -f /etc/apt/sources.list.d/sovrin.list*

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        fetch-depth: 0

    - name: Get the latest release version
      run: |
        GITVERSION="$(git describe --tags | awk -F'.' '{print $$1}')"
        export GITVERSION
        echo "GITVERSION=$GITVERSION" >> "$GITHUB_ENV"

    - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 #v5.6.0
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set up NodeJS ${{ env.NODEJS_VERSION }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
      with:
        node-version: ${{ env.NODEJS_VERSION }}

    - run: npm run configure

    - name: build-cactus-plugin-ledger-connector-corda-kotlin-client
      run: |
        WDIR=$(pwd)
        cd "${WDIR}/packages/cactus-plugin-ledger-connector-corda/src/main/kotlin/generated/openapi/kotlin-client"
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: publish-cactus-plugin-ledger-connector-corda-kotlin-client
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: cactus-plugin-ledger-connector-corda-kotlin-client-${{ env.GITVERSION }}.jar
        path: packages/cactus-plugin-ledger-connector-corda/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar

    - name: build-cactus-cmd-api-server-kotlin-client
      run: |
        WDIR=$(pwd)
        cd "${WDIR}/packages/cactus-cmd-api-server/src/main/kotlin/generated/openapi/kotlin-client"
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: publish-cactus-cmd-api-server-kotlin-client
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: cactus-cmd-api-server-kotlin-client-${{ env.GITVERSION }}.jar
        path: packages/cactus-cmd-api-server/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar

    - name: build-cactus-core-api-kotlin-client
      run: |
        WDIR=$(pwd)
        cd "${WDIR}/packages/cactus-core-api/src/main/kotlin/generated/openapi/kotlin-client"
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: publish-cactus-core-api-kotlin-client
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: cactus-core-api-kotlin-client-${{ env.GITVERSION }}.jar
        path: packages/cactus-core-api/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar

    - name: build-cactus-plugin-keychain-memory-kotlin-client
      run: |
        WDIR=$(pwd)
        cd "${WDIR}/packages/cactus-plugin-keychain-memory/src/main/kotlin/generated/openapi/kotlin-client"
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: publish-cactus-plugin-keychain-memory-kotlin-client
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: cactus-plugin-keychain-memory-kotlin-client-${{ env.GITVERSION }}.jar
        path: packages/cactus-plugin-keychain-memory/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar

    - name: build-cactus-plugin-ledger-connector-fabric-kotlin-client
      run: |
        WDIR=$(pwd)
        cd "${WDIR}/packages/cactus-plugin-ledger-connector-fabric/src/main/kotlin/generated/openapi/kotlin-client"
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: publish-cactus-plugin-ledger-connector-fabric-kotlin-client
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: cactus-plugin-ledger-connector-fabric-kotlin-client-${{ env.GITVERSION }}.jar
        path: packages/cactus-plugin-ledger-connector-fabric/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar

    - name: build-cactus-plugin-satp-hermes-kotlin-client
      run: |
        WDIR=$(pwd)
        cd "${WDIR}/packages/cactus-plugin-satp-hermes/src/main/kotlin/generated/openapi/kotlin-client"
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: publish-cactus-plugin-satp-hermes-kotlin-client
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: cactus-plugin-satp-hermes-kotlin-client-${{ env.GITVERSION }}.jar
        path: packages/cactus-plugin-satp-hermes/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar

    - name: build-cactus-plugin-object-store-ipfs-kotlin-client
      run: |
        WDIR=$(pwd)
        cd "${WDIR}/extensions/cactus-plugin-object-store-ipfs/src/main/kotlin/generated/openapi/kotlin-client"
        chmod +x gradlew
        ./gradlew clean
        ./gradlew build

    - name: publish-cactus-plugin-object-store-ipfs-kotlin-client
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
      with:
        name: cactus-plugin-object-store-ipfs-kotlin-client-${{ env.GITVERSION }}.jar
        path: extensions/cactus-plugin-object-store-ipfs/src/main/kotlin/generated/openapi/kotlin-client/build/libs/kotlin-client-1.0.0.jar
