deploy-contracts: deploy-contract-network1 deploy-contract-network2

deploy-contract-network1:
	BESU_NETWORK_HOST=localhost BESU_NETWORK_PORT=8545 npm run deploy-contract

deploy-contract-network2:
	BESU_NETWORK_HOST=localhost BESU_NETWORK_PORT=9544 npm run deploy-contract
